### ISSUE TITLE
unable to add package via meteor add command

### ISSUE THREAD

**Issue by nelsonomuto** [foxdog-studios/meteor-webrtc#1]
meteor add fds:webrtc
Could not download package arunoda:streams@0.1.17: tunneling socket could not be established, cause=socket hang up
Could not download package fds:webrtc@2.1.0: tunneling socket could not be established, cause=socket hang up
Package arunoda:streams has no compatible build for version 0.1.17

**Comment by nelsonomuto** [comment]
I'm on Meteor 1.0

**Comment by eldog** [comment]
I just tried adding it on a fresh project and it worked (Meteor 1.0.2)

Could it be this "tunneling socket could not be established" error?

Looking up the error suggests it could it be something with to do with a proxy?
