### ISSUE TITLE
I want to record a streaming session into mp4 or any possible video format. Could you guide me where should I start ?

### ISSUE THREAD

**Issue by meepeek** [foxdog-studios/meteor-webrtc#3]

**Comment by meepeek** [comment]
Anyone here ?

**Comment by eldog** [comment]
Sorry for the delay. Recording a video has been done with https://www.webrtc-experiment.com/RecordRTC/ - I haven't looked to much into it myself.

Also see this StackOverflow answer http://stackoverflow.com/questions/18509385/html-5-video-recording-and-storing-a-stream

**Comment by meepeek** [comment]
Thank you for the resource. That was really helpful.
