### ISSUE TITLE
Can I record the the video chats somehow?

### ISSUE THREAD

**Issue by ggndpsingh-old** [foxdog-studios/meteor-webrtc#8]
Is there a way to record and save the video chats between two people?

**Comment by eldog** [comment]
You'd need to do that outside of Meteor.

You can do it client side with https://github.com/streamproc/MediaStreamRecorder

Or try recording on a server using something like Kurento http://www.kurento.org/docs/5.1.1/tutorials.html#tutorial-5-webrtc-one-to-one-video-call-with-recording-and-filtering

**Comment by ggndpsingh-old** [comment]
Thanks for the quick reply eldog ... Love the name btw. I'll give that a try after I get the basic calling to work which I cant. I'm using jQuery and I just converted your coffeescript code jQuery and inserted it as is to my project. I am not getting any error buts I can also cannot get a connections between two windows in the same room? Is there anything else I need to change to make it work? 

PS I'm only using the home.coffee and home.html pages from your example code.

It might turn out to be something very simple but I am fairly new to all this so I'll appreciate the help. Thanks
